apiVersion: v1
kind: Service
metadata:
  name: flowlog-test-service
spec:
  selector:
    app: flowlog-test-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowlog-test-app
spec:
  selector:
    matchLabels:
      app: flowlog-test-app
  replicas: 5
  template:
    metadata:
      labels:
        app: flowlog-test-app
    spec:
      containers:
      - name: flowlog-test-app
        image: flowlog-kubernetes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/uploads  
          name: uploads-volume
      volumes:
      - name: uploads-volume
        emptyDir: {} 